
prefectureMap = {
    "01": "Hokkaido",
    "02": "Aomori",
    "03": "Iwate",
    "04": "Miyagi",
    "05": "Akita",
    "06": "Yamagata",
    "07": "Fukushima",
    "08": "Ibaraki",
    "09": "Tochigi",
    "10": "Gunma",
    "11": "Saitama",
    "12": "Chiba",
    "13": "Tokyo",
    "14": "Kanagawa",
    "15": "Niigata",
    "16": "Toyama",
    "17": "Ishikawa",
    "18": "Fukui",
    "19": "Yamanashi",
    "20": "Nagano",
    "21": "Gifu",
    "22": "Shizuoka",
    "23": "Aichi",
    "24": "Mie",
    "25": "Shiga",
    "26": "Kyoto",
    "27": "Osaka",
    "28": "Hyogo",
    "29": "Nara",
    "30": "Wakayama",
    "31": "Tottori",
    "32": "Shimane",
    "33": "Okayama",
    "34": "Hiroshima",
    "35": "Yamaguchi",
    "36": "Tokushima",
    "37": "Kagawa",
    "38": "Ehime",
    "39": "Kochi",
    "40": "Fukuoka",
    "41": "Saga",
    "42": "Nagasaki",
    "43": "Kumamoto",
    "44": "Oita",
    "45": "Miyazaki",
    "46": "Kagoshima",
    "47": "Okinawa"
}

nameMap = {
    "JP.HS":"Hiroshima",
    "JP.OY":"Okayama",
    "JP.SM":"Shimane",
    "JP.TT":"Tottori",
    "JP.YC":"Yamaguchi",
    "JP.SG":"Saga",
    "JP.FO":"Fukuoka",
    "JP.KM":"Kumamoto",
    "JP.MZ":"Miyazaki",
    "JP.EH":"Ehime",
    "JP.KG":"Kagawa",
    "JP.KC":"Kochi",
    "JP.OT":"Oita",
    "JP.TS":"Tokushima",
    "JP.AI":"Aichi",
    "JP.GF":"Gifu",
    "JP.IS":"Ishikawa",
    "JP.ME":"Mie",
    "JP.NN":"Nagano",
    "JP.SZ":"Shizuoka",
    "JP.TY":"Toyama",
    "JP.HK":"Hokkaido",
    "JP.FI":"Fukui",
    "JP.HG":"Hyogo",
    "JP.KY":"Kyoto",
    "JP.NR":"Nara",
    "JP.OS":"Osaka",
    "JP.SH":"Shiga",
    "JP.WK":"Wakayama",
    "JP.CH":"Chiba",
    "JP.IB":"Ibaraki",
    "JP.KN":"Kanagawa",
    "JP.ST":"Saitama",
    "JP.TC":"Tochigi",
    "JP.TK":"Tokyo",
    "JP.YN":"Yamanashi",
    "JP.AK":"Akita",
    "JP.AO":"Aomori",
    "JP.FS":"Fukushima",
    "JP.IW":"Iwate",
    "JP.MG":"Miyagi",
    "JP.NI":"Niigata",
    "JP.YT":"Yamagata",
    "JP.NS":"Nagasaki",
    "JP.KS":"Kagoshima",
    "JP.ON":"Okinawa",
    "JP.GM":"Gunma"
}

if __name__ == "__main__":
    new_pre = {}
    for key, val in prefectureMap.items():
        new_pre[val] = key

    new_name = {}
    for key, val in nameMap.items():
        new_name[val] = key

    for key, val in prefectureMap.items():
        print '"{0}": "{1}",'.format(key, new_name[val])
